variable "common" {}
variable "resource_group_name" {}
variable "app_service" {}
variable "app_settings" {}
variable "allowed_origins" {}
variable "allowed_cidr" {}
variable "app_service_plan" {}
variable "identity" {}
variable "frontdoor_profile" {}
variable "tenant_id" {}
variable "auth_settings_v2" {}
